### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by Kn99HN** [NicholasLYang/courses#1]
I got this error. How should I come around fixing this?

```
Failed to compile.

./src/App.tsx
Module not found: Can't resolve '/Users/khanhnguyen/Documents/GitHub/courses/node_modules/babel-preset-react-app/node_modules/@babel/runtime/hel
pers/esm/objectSpread2' in '/Users/khanhnguyen/Documents/GitHub/courses/src'
```

**Comment by NicholasLYang** [comment]
Hmm interesting error. I assume you ran `npm install`?

**Comment by Kn99HN** [comment]
I ran ```yarn```

**Comment by NicholasLYang** [comment]
That shouldn't make a difference, but perhaps try `npm install`?

**Comment by Kn99HN** [comment]
I tried it and the same error is still there

**Comment by Kn99HN** [comment]
Oh, nvm. I rerun with ```yarn``` and it's fixed

**Comment by NicholasLYang** [comment]
Yeah you can also delete `node_modules` and rerun. That's a common way to fix these sort of issues
