### ISSUE TITLE
Section Descriptions

### ISSUE THREAD

**Issue by NicholasLYang** [NicholasLYang/courses#3]
We need a way to display section descriptions. I'm not sure if we have enough space in the courses list, so I'm thinking we make a `CoursePage` that includes sections with descriptions. Open to any design ideas

**Comment by Kn99HN** [comment]
Can we do it such that the course description shows up once in the title with credit and such. Then there is a drop down menu for sections?

**Comment by NicholasLYang** [comment]
Hmm, perhaps. But I have a feeling users will want to see a bunch of sections at once. Like just from my experience, I like scrolling down through sections and seeing what fits into my schedule. I wouldn't want to use a dropdown menu to change sections

**Comment by Kn99HN** [comment]
For sure. I was thinking something like [this](https://app.testudo.umd.edu/soc/search?courseId=CMSC131&sectionId=&termId=202008&_openSectionsOnly=on&creditCompare=&credits=&courseLevelFilter=ALL&instructor=&_facetoface=on&_blended=on&_online=on&courseStartCompare=&courseStartHour=&courseStartMin=&courseStartAM=&courseEndHour=&courseEndMin=&courseEndAM=&teachingCenter=ALL&_classDay1=on&_classDay2=on&_classDay3=on&_classDay4=on&_classDay5=on). The drop down menu shows all the sections then the catalog itself shows the min and max credit, descriptions, and other genral information true for all the sections

**Comment by NicholasLYang** [comment]
I'm not sure if section descriptions are necessarily the same for all sections. For instance, with special topics courses, we need to display descriptions specific to that section.

**Comment by NicholasLYang** [comment]
I'm gonna close this in favor of a course page
